apiVersion: apps/v1          # The version of the Kubernetes API
kind: Deployment             # The type of "Lego brick" we are building
metadata:
  name: app1-deploy          # The name of this Manager
spec:
  replicas: 1                # How many workers (Pods) should be alive?
  selector:
    matchLabels:
      app: app1              # The Manager only watches Pods with this label
  template:                  # This is the "Blueprint" for the Pod
    metadata:
      labels:
        app: app1            # We STAMP the Pod with this label so the Manager finds it
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine  # The actual software (a tiny web server)
        ports:
        - containerPort: 80  # The "window" the software listens on