
VAGRANTFILE_CONFIGURATION_VERSION = "2"
Vagrant.configure(VAGRANTFILE_CONFIGURATION_VERSION) do |config|


  master_ip = "192.168.56.110"

  scriptS = <<-SCRIPT
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_EXEC="server \
    --node-ip=#{master_ip} \
    --flannel-iface=eth1 \
    --write-kubeconfig-mode 644" \
    sh -
      
    cp /var/lib/rancher/k3s/server/token /vagrant/token
    echo "alias k='sudo /usr/local/bin/k3s kubectl'" >> /home/vagrant/.bashrc
  SCRIPT


  config.vm.define "fmehdaouS" do |node|
    node.vm.box = "centos/stream9"
    node.vm.box_version = "20260331.0"
    node.vm.hostname = "fmehdaouS"
    node.vm.network "private_network", ip: master_ip
    node.vm.provider "virtualbox" do |v|
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    v.name = "fmehdaouS"
    v.memory = 1024
    v.cpus = 2
    end

    node.vm.provision "shell",
      inline: scriptS
  end



end