Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream9"
  config.vm.define "moharrasS" do |server|
    server.vm.hostname = "moharrasS"
    server.vm.provider "virtualbox" do |vb|
      vb.cpus = 4
      vb.memory = "4096"
      server.vm.network "private_network", ip: "192.168.56.110"
    end
  end
  config.vm.define "moharrasSW" do |worker|
    worker.vm.hostname = "moharrasSW"
    worker.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
      worker.vm.network "private_network", ip: "192.168.56.111"
    end
  end
end