
VAGRANTFILE_CONFIGURATION_VERSION = "2"
Vagrant.configure(VAGRANTFILE_CONFIGURATION_VERSION) do |config|
  master_ip = "192.168.56.110"
  worker_ip = "192.168.56.111"

  config.vm.define "fmehdaouS" do |node|
    node.vm.box = "debian/bookworm64"
    node.vm.box_version = "12.20250126.1"
    node.vm.hostname = "fmehdaouS"
    node.vm.network "private_network", ip: master_ip
    node.vm.synced_folder "./confs", "/vagrant"
    node.vm.provider "virtualbox" do |v|
    v.name = "fmehdaouS"
    v.memory = 2048
    v.cpus = 2
    end

    node.vm.provision "shell", path: "scripts/install-server.sh" , env: { "master_ip" => master_ip }
  end

   config.vm.define "fmehdaouSW" do |node|
    node.vm.box = "debian/bookworm64"
    node.vm.box_version = "12.20250126.1"
    node.vm.hostname = "fmehdaouSW"
    node.vm.network "private_network", ip: worker_ip
    node.vm.synced_folder "./confs", "/vagrant"
    node.vm.provider "virtualbox" do |v|
    v.name = "fmehdaouSW"
    v.memory = 512
    v.cpus = 1
    end
    node.vm.provision "shell", path: "scripts/install-worker.sh", env: { "master_ip" => master_ip ,"worker_ip" => worker_ip,  }
  end

end