Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream9"
  config.vm.define "moharrasS" do |server|
    server.vm.hostname = "moharrasS"
    server.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        # Forwarding for Argo CD UI and the Web App
        server.vm.network "forwarded_port", guest: 8080, host: 8080
        server.vm.network "forwarded_port", guest: 8081, host: 8081
    end
    server.vm.provision "shell", path: "scripts/install.sh"
  end
end